vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pieces:
            uri_prefix: /files/
            upload_destination: '%kernel.project_dir%/public/files/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer